name: CI-Check

on:
  push:
    branches: [ "master", "branch_test" ]
  pull_request:
    branches: [ "master", "branch_test" ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Jest
        run: npm install jest --save-dev

      - name: Executar Testes Unitários
        run: ./node_modules/.bin/jest projeto.test.js